services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_live_Y2xlcmsubGFqdXBvLmRlJA"
    working_dir: /app
    image: t3-app
    networks:
      - Aliases
    environment:
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/www
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsubGFqdXBvLmRlJA
      - CLERK_SECRET_KEY=

networks:
  Aliases:
    external: true
